services:
  db:
    build:
      context: .
      dockerfile: ./ci/docker/Dockerfile.local.db
    env_file:
      - .env
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - default

  api:
    build:
      context: .
      dockerfile: ./ci/docker/Dockerfile.local.api
    env_file:
      - .env
    ports:
      - ${API_PORT}:1323
    volumes:
      - ./:/app
    networks:
      - default
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: ./ci/docker/Dockerfile.local.web
    ports:
      - ${WEB_PORT}:5173
    volumes:
      - ./web:/app

volumes:
  db-data:
    driver: local