// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package cashbunny_entry

import (
	"database/sql"
	"time"
)

type CashbunnyEntry struct {
	ID            uint32
	UserID        uint32
	AccountID     uint32
	TransactionID uint32
	Amount        float64
	Currency      string
	TransactedAt  time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     sql.NullTime
}
