// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package cashbunny_entry

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateEntry(ctx context.Context, db DBTX, arg CreateEntryParams) (sql.Result, error)
	ListEntriesByTransactionID(ctx context.Context, db DBTX, arg ListEntriesByTransactionIDParams) ([]*CashbunnyEntry, error)
}

var _ Querier = (*Queries)(nil)
