// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package auth_repository

import (
	"database/sql"
	"time"
)

type User struct {
	ID        uint32
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type UserPassword struct {
	ID           uint32
	UserID       uint32
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}
