// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package oapi

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// CashbunnyUserPreference Model defining user's cashbunny preferences such as default currency etc.
type CashbunnyUserPreference struct {
	UserCurrencies []string `json:"user_currencies"`
}

// Error Error code and underlying errors
type Error struct {
	// Message A useful message describing the error
	Message            string            `json:"message"`
	ValidationMessages map[string]string `json:"validation_messages"`
}

// User defines model for user.
type User struct {
	CreatedAt  string `json:"created_at"`
	Id         uint32 `json:"id"`
	LoggedInAt string `json:"logged_in_at"`
	Name       string `json:"name"`
}

// UserSystemPreference Model defining user system preferences such as language, time zone etc.
type UserSystemPreference struct {
	Language *string `json:"language"`
}

// CreateUserJSONBody defines parameters for CreateUser.
type CreateUserJSONBody struct {
	// Email must be a valid email
	Email string `json:"email" validate:"email"`

	// Password must be between 8 to 72 characters, and contain a letter, number and a special character
	Password string `json:"password" validate:"_password"`

	// Username must be between 3 to 50 alphanumerical characters
	Username string `json:"username" validate:"alphanum,min=3,max=50"`
}

// CreateJWTTokenJSONBody defines parameters for CreateJWTToken.
type CreateJWTTokenJSONBody struct {
	Password string `json:"password"`

	// Username must be alphanumerical characters, with maximum 50 character count
	Username string `json:"username" validate:"alphanum,max=50"`
}

// RepeatJSONBody defines parameters for Repeat.
type RepeatJSONBody struct {
	// Message Some message you want to be sent back
	Message string `json:"message"`
}

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody CreateUserJSONBody

// CreateJWTTokenJSONRequestBody defines body for CreateJWTToken for application/json ContentType.
type CreateJWTTokenJSONRequestBody CreateJWTTokenJSONBody

// RepeatJSONRequestBody defines body for Repeat for application/json ContentType.
type RepeatJSONRequestBody RepeatJSONBody

// UpdateUserSystemPreferenceJSONRequestBody defines body for UpdateUserSystemPreference for application/json ContentType.
type UpdateUserSystemPreferenceJSONRequestBody = UserSystemPreference
