// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /api/v1/auth)
	CreateUser(ctx echo.Context) error

	// (POST /api/v1/auth/token)
	CreateJWTToken(ctx echo.Context) error

	// (PUT /api/v1/auth/token)
	RefreshJWTToken(ctx echo.Context) error

	// (GET /api/v1/ping)
	Ping(ctx echo.Context) error

	// (POST /api/v1/repeat)
	Repeat(ctx echo.Context) error

	// (DELETE /api/v1/secure/auth/refresh-token)
	DeleteJWTRefreshToken(ctx echo.Context) error

	// (POST /api/v1/secure/auth/refresh-token)
	CreateJWTRefreshToken(ctx echo.Context) error

	// (DELETE /api/v1/secure/auth/token)
	DeleteJWTToken(ctx echo.Context) error

	// (GET /api/v1/secure/cashbunny/accounts)
	GetCashbunnyAccounts(ctx echo.Context) error

	// (POST /api/v1/secure/cashbunny/accounts)
	CreateCashbunnyAccount(ctx echo.Context) error

	// (DELETE /api/v1/secure/cashbunny/accounts/{accountId})
	DeleteCashbunnyAccount(ctx echo.Context, accountId uint32) error

	// (PUT /api/v1/secure/cashbunny/accounts/{accountId})
	UpdateCashbunnyAccount(ctx echo.Context, accountId uint32) error

	// (GET /api/v1/secure/cashbunny/currencies)
	GetCashbunnySupportedCurrencies(ctx echo.Context) error

	// (GET /api/v1/secure/cashbunny/overview)
	GetCashbunnyOverview(ctx echo.Context, params GetCashbunnyOverviewParams) error

	// (GET /api/v1/secure/cashbunny/user-preferences)
	GetCashbunnyUserPreference(ctx echo.Context) error

	// (POST /api/v1/secure/cashbunny/user-preferences)
	CreateCashbunnyDefaultUserPreference(ctx echo.Context) error

	// (GET /api/v1/secure/system-preferences)
	GetUserSystemPreference(ctx echo.Context) error

	// (POST /api/v1/secure/system-preferences)
	CreateDefaultUserSystemPreference(ctx echo.Context) error

	// (PUT /api/v1/secure/system-preferences)
	UpdateUserSystemPreference(ctx echo.Context) error

	// (GET /api/v1/secure/user)
	GetUser(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// CreateUser converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateUser(ctx)
	return err
}

// CreateJWTToken converts echo context to params.
func (w *ServerInterfaceWrapper) CreateJWTToken(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateJWTToken(ctx)
	return err
}

// RefreshJWTToken converts echo context to params.
func (w *ServerInterfaceWrapper) RefreshJWTToken(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RefreshJWTToken(ctx)
	return err
}

// Ping converts echo context to params.
func (w *ServerInterfaceWrapper) Ping(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Ping(ctx)
	return err
}

// Repeat converts echo context to params.
func (w *ServerInterfaceWrapper) Repeat(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Repeat(ctx)
	return err
}

// DeleteJWTRefreshToken converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteJWTRefreshToken(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteJWTRefreshToken(ctx)
	return err
}

// CreateJWTRefreshToken converts echo context to params.
func (w *ServerInterfaceWrapper) CreateJWTRefreshToken(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateJWTRefreshToken(ctx)
	return err
}

// DeleteJWTToken converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteJWTToken(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteJWTToken(ctx)
	return err
}

// GetCashbunnyAccounts converts echo context to params.
func (w *ServerInterfaceWrapper) GetCashbunnyAccounts(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCashbunnyAccounts(ctx)
	return err
}

// CreateCashbunnyAccount converts echo context to params.
func (w *ServerInterfaceWrapper) CreateCashbunnyAccount(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateCashbunnyAccount(ctx)
	return err
}

// DeleteCashbunnyAccount converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteCashbunnyAccount(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "accountId" -------------
	var accountId uint32

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", ctx.Param("accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter accountId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteCashbunnyAccount(ctx, accountId)
	return err
}

// UpdateCashbunnyAccount converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateCashbunnyAccount(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "accountId" -------------
	var accountId uint32

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", ctx.Param("accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter accountId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateCashbunnyAccount(ctx, accountId)
	return err
}

// GetCashbunnySupportedCurrencies converts echo context to params.
func (w *ServerInterfaceWrapper) GetCashbunnySupportedCurrencies(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCashbunnySupportedCurrencies(ctx)
	return err
}

// GetCashbunnyOverview converts echo context to params.
func (w *ServerInterfaceWrapper) GetCashbunnyOverview(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCashbunnyOverviewParams
	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameter("form", true, false, "from", ctx.QueryParams(), &params.From)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter from: %s", err))
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameter("form", true, false, "to", ctx.QueryParams(), &params.To)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter to: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCashbunnyOverview(ctx, params)
	return err
}

// GetCashbunnyUserPreference converts echo context to params.
func (w *ServerInterfaceWrapper) GetCashbunnyUserPreference(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCashbunnyUserPreference(ctx)
	return err
}

// CreateCashbunnyDefaultUserPreference converts echo context to params.
func (w *ServerInterfaceWrapper) CreateCashbunnyDefaultUserPreference(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateCashbunnyDefaultUserPreference(ctx)
	return err
}

// GetUserSystemPreference converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserSystemPreference(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserSystemPreference(ctx)
	return err
}

// CreateDefaultUserSystemPreference converts echo context to params.
func (w *ServerInterfaceWrapper) CreateDefaultUserSystemPreference(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateDefaultUserSystemPreference(ctx)
	return err
}

// UpdateUserSystemPreference converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateUserSystemPreference(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateUserSystemPreference(ctx)
	return err
}

// GetUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetUser(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUser(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/api/v1/auth", wrapper.CreateUser)
	router.POST(baseURL+"/api/v1/auth/token", wrapper.CreateJWTToken)
	router.PUT(baseURL+"/api/v1/auth/token", wrapper.RefreshJWTToken)
	router.GET(baseURL+"/api/v1/ping", wrapper.Ping)
	router.POST(baseURL+"/api/v1/repeat", wrapper.Repeat)
	router.DELETE(baseURL+"/api/v1/secure/auth/refresh-token", wrapper.DeleteJWTRefreshToken)
	router.POST(baseURL+"/api/v1/secure/auth/refresh-token", wrapper.CreateJWTRefreshToken)
	router.DELETE(baseURL+"/api/v1/secure/auth/token", wrapper.DeleteJWTToken)
	router.GET(baseURL+"/api/v1/secure/cashbunny/accounts", wrapper.GetCashbunnyAccounts)
	router.POST(baseURL+"/api/v1/secure/cashbunny/accounts", wrapper.CreateCashbunnyAccount)
	router.DELETE(baseURL+"/api/v1/secure/cashbunny/accounts/:accountId", wrapper.DeleteCashbunnyAccount)
	router.PUT(baseURL+"/api/v1/secure/cashbunny/accounts/:accountId", wrapper.UpdateCashbunnyAccount)
	router.GET(baseURL+"/api/v1/secure/cashbunny/currencies", wrapper.GetCashbunnySupportedCurrencies)
	router.GET(baseURL+"/api/v1/secure/cashbunny/overview", wrapper.GetCashbunnyOverview)
	router.GET(baseURL+"/api/v1/secure/cashbunny/user-preferences", wrapper.GetCashbunnyUserPreference)
	router.POST(baseURL+"/api/v1/secure/cashbunny/user-preferences", wrapper.CreateCashbunnyDefaultUserPreference)
	router.GET(baseURL+"/api/v1/secure/system-preferences", wrapper.GetUserSystemPreference)
	router.POST(baseURL+"/api/v1/secure/system-preferences", wrapper.CreateDefaultUserSystemPreference)
	router.PUT(baseURL+"/api/v1/secure/system-preferences", wrapper.UpdateUserSystemPreference)
	router.GET(baseURL+"/api/v1/secure/user", wrapper.GetUser)

}

type CreateUserRequestObject struct {
	Body *CreateUserJSONRequestBody
}

type CreateUserResponseObject interface {
	VisitCreateUserResponse(w http.ResponseWriter) error
}

type CreateUser202Response struct {
}

func (response CreateUser202Response) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type CreateUser400JSONResponse Error

func (response CreateUser400JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateJWTTokenRequestObject struct {
	Body *CreateJWTTokenJSONRequestBody
}

type CreateJWTTokenResponseObject interface {
	VisitCreateJWTTokenResponse(w http.ResponseWriter) error
}

type CreateJWTToken200ResponseHeaders struct {
	SetCookie string
}

type CreateJWTToken200Response struct {
	Headers CreateJWTToken200ResponseHeaders
}

func (response CreateJWTToken200Response) VisitCreateJWTTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)
	return nil
}

type CreateJWTToken400JSONResponse Error

func (response CreateJWTToken400JSONResponse) VisitCreateJWTTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateJWTToken403JSONResponse Error

func (response CreateJWTToken403JSONResponse) VisitCreateJWTTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type RefreshJWTTokenRequestObject struct {
}

type RefreshJWTTokenResponseObject interface {
	VisitRefreshJWTTokenResponse(w http.ResponseWriter) error
}

type RefreshJWTToken200ResponseHeaders struct {
	SetCookie string
}

type RefreshJWTToken200Response struct {
	Headers RefreshJWTToken200ResponseHeaders
}

func (response RefreshJWTToken200Response) VisitRefreshJWTTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)
	return nil
}

type PingRequestObject struct {
}

type PingResponseObject interface {
	VisitPingResponse(w http.ResponseWriter) error
}

type Ping200JSONResponse struct {
	// Message Pong!
	Message string `json:"message"`
}

func (response Ping200JSONResponse) VisitPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RepeatRequestObject struct {
	Body *RepeatJSONRequestBody
}

type RepeatResponseObject interface {
	VisitRepeatResponse(w http.ResponseWriter) error
}

type Repeat200JSONResponse struct {
	// Message The message you sent
	Message string `json:"message"`
}

func (response Repeat200JSONResponse) VisitRepeatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteJWTRefreshTokenRequestObject struct {
}

type DeleteJWTRefreshTokenResponseObject interface {
	VisitDeleteJWTRefreshTokenResponse(w http.ResponseWriter) error
}

type DeleteJWTRefreshToken204ResponseHeaders struct {
	SetCookie string
}

type DeleteJWTRefreshToken204Response struct {
	Headers DeleteJWTRefreshToken204ResponseHeaders
}

func (response DeleteJWTRefreshToken204Response) VisitDeleteJWTRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(204)
	return nil
}

type CreateJWTRefreshTokenRequestObject struct {
}

type CreateJWTRefreshTokenResponseObject interface {
	VisitCreateJWTRefreshTokenResponse(w http.ResponseWriter) error
}

type CreateJWTRefreshToken200ResponseHeaders struct {
	SetCookie string
}

type CreateJWTRefreshToken200Response struct {
	Headers CreateJWTRefreshToken200ResponseHeaders
}

func (response CreateJWTRefreshToken200Response) VisitCreateJWTRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)
	return nil
}

type CreateJWTRefreshToken403JSONResponse Error

func (response CreateJWTRefreshToken403JSONResponse) VisitCreateJWTRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteJWTTokenRequestObject struct {
}

type DeleteJWTTokenResponseObject interface {
	VisitDeleteJWTTokenResponse(w http.ResponseWriter) error
}

type DeleteJWTToken204ResponseHeaders struct {
	SetCookie string
}

type DeleteJWTToken204Response struct {
	Headers DeleteJWTToken204ResponseHeaders
}

func (response DeleteJWTToken204Response) VisitDeleteJWTTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(204)
	return nil
}

type GetCashbunnyAccountsRequestObject struct {
}

type GetCashbunnyAccountsResponseObject interface {
	VisitGetCashbunnyAccountsResponse(w http.ResponseWriter) error
}

type GetCashbunnyAccounts200JSONResponse struct {
	Accounts []CashbunnyAccount `json:"accounts"`
}

func (response GetCashbunnyAccounts200JSONResponse) VisitGetCashbunnyAccountsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateCashbunnyAccountRequestObject struct {
	Body *CreateCashbunnyAccountJSONRequestBody
}

type CreateCashbunnyAccountResponseObject interface {
	VisitCreateCashbunnyAccountResponse(w http.ResponseWriter) error
}

type CreateCashbunnyAccount200Response struct {
}

func (response CreateCashbunnyAccount200Response) VisitCreateCashbunnyAccountResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type CreateCashbunnyAccount400JSONResponse Error

func (response CreateCashbunnyAccount400JSONResponse) VisitCreateCashbunnyAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteCashbunnyAccountRequestObject struct {
	AccountId uint32 `json:"accountId"`
}

type DeleteCashbunnyAccountResponseObject interface {
	VisitDeleteCashbunnyAccountResponse(w http.ResponseWriter) error
}

type DeleteCashbunnyAccount200Response struct {
}

func (response DeleteCashbunnyAccount200Response) VisitDeleteCashbunnyAccountResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type UpdateCashbunnyAccountRequestObject struct {
	AccountId uint32 `json:"accountId"`
	Body      *UpdateCashbunnyAccountJSONRequestBody
}

type UpdateCashbunnyAccountResponseObject interface {
	VisitUpdateCashbunnyAccountResponse(w http.ResponseWriter) error
}

type UpdateCashbunnyAccount200Response struct {
}

func (response UpdateCashbunnyAccount200Response) VisitUpdateCashbunnyAccountResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type UpdateCashbunnyAccount400JSONResponse Error

func (response UpdateCashbunnyAccount400JSONResponse) VisitUpdateCashbunnyAccountResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetCashbunnySupportedCurrenciesRequestObject struct {
}

type GetCashbunnySupportedCurrenciesResponseObject interface {
	VisitGetCashbunnySupportedCurrenciesResponse(w http.ResponseWriter) error
}

type GetCashbunnySupportedCurrencies200JSONResponse struct {
	CurrenciesAndGrapheme map[string]string `json:"currencies_and_grapheme"`
}

func (response GetCashbunnySupportedCurrencies200JSONResponse) VisitGetCashbunnySupportedCurrenciesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCashbunnyOverviewRequestObject struct {
	Params GetCashbunnyOverviewParams
}

type GetCashbunnyOverviewResponseObject interface {
	VisitGetCashbunnyOverviewResponse(w http.ResponseWriter) error
}

type GetCashbunnyOverview200JSONResponse CashbunnyOverview

func (response GetCashbunnyOverview200JSONResponse) VisitGetCashbunnyOverviewResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCashbunnyUserPreferenceRequestObject struct {
}

type GetCashbunnyUserPreferenceResponseObject interface {
	VisitGetCashbunnyUserPreferenceResponse(w http.ResponseWriter) error
}

type GetCashbunnyUserPreference200JSONResponse struct {
	// UserPreference Model defining user's Cashbunny preferences such as default currency etc.
	UserPreference CashbunnyUserPreference `json:"user_preference"`
}

func (response GetCashbunnyUserPreference200JSONResponse) VisitGetCashbunnyUserPreferenceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCashbunnyUserPreference404Response struct {
}

func (response GetCashbunnyUserPreference404Response) VisitGetCashbunnyUserPreferenceResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type CreateCashbunnyDefaultUserPreferenceRequestObject struct {
}

type CreateCashbunnyDefaultUserPreferenceResponseObject interface {
	VisitCreateCashbunnyDefaultUserPreferenceResponse(w http.ResponseWriter) error
}

type CreateCashbunnyDefaultUserPreference200JSONResponse struct {
	// UserPreference Model defining user's Cashbunny preferences such as default currency etc.
	UserPreference CashbunnyUserPreference `json:"user_preference"`
}

func (response CreateCashbunnyDefaultUserPreference200JSONResponse) VisitCreateCashbunnyDefaultUserPreferenceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUserSystemPreferenceRequestObject struct {
}

type GetUserSystemPreferenceResponseObject interface {
	VisitGetUserSystemPreferenceResponse(w http.ResponseWriter) error
}

type GetUserSystemPreference200JSONResponse struct {
	// UserSystemPreference Model defining user system preferences such as language, time zone etc.
	UserSystemPreference UserSystemPreference `json:"user_system_preference"`
}

func (response GetUserSystemPreference200JSONResponse) VisitGetUserSystemPreferenceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUserSystemPreference404Response struct {
}

func (response GetUserSystemPreference404Response) VisitGetUserSystemPreferenceResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type CreateDefaultUserSystemPreferenceRequestObject struct {
}

type CreateDefaultUserSystemPreferenceResponseObject interface {
	VisitCreateDefaultUserSystemPreferenceResponse(w http.ResponseWriter) error
}

type CreateDefaultUserSystemPreference200JSONResponse struct {
	// UserSystemPreference Model defining user system preferences such as language, time zone etc.
	UserSystemPreference UserSystemPreference `json:"user_system_preference"`
}

func (response CreateDefaultUserSystemPreference200JSONResponse) VisitCreateDefaultUserSystemPreferenceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateUserSystemPreferenceRequestObject struct {
	Body *UpdateUserSystemPreferenceJSONRequestBody
}

type UpdateUserSystemPreferenceResponseObject interface {
	VisitUpdateUserSystemPreferenceResponse(w http.ResponseWriter) error
}

type UpdateUserSystemPreference200JSONResponse struct {
	// UserSystemPreference Model defining user system preferences such as language, time zone etc.
	UserSystemPreference UserSystemPreference `json:"user_system_preference"`
}

func (response UpdateUserSystemPreference200JSONResponse) VisitUpdateUserSystemPreferenceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUserRequestObject struct {
}

type GetUserResponseObject interface {
	VisitGetUserResponse(w http.ResponseWriter) error
}

type GetUser200JSONResponse struct {
	User User `json:"user"`
}

func (response GetUser200JSONResponse) VisitGetUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /api/v1/auth)
	CreateUser(ctx context.Context, request CreateUserRequestObject) (CreateUserResponseObject, error)

	// (POST /api/v1/auth/token)
	CreateJWTToken(ctx context.Context, request CreateJWTTokenRequestObject) (CreateJWTTokenResponseObject, error)

	// (PUT /api/v1/auth/token)
	RefreshJWTToken(ctx context.Context, request RefreshJWTTokenRequestObject) (RefreshJWTTokenResponseObject, error)

	// (GET /api/v1/ping)
	Ping(ctx context.Context, request PingRequestObject) (PingResponseObject, error)

	// (POST /api/v1/repeat)
	Repeat(ctx context.Context, request RepeatRequestObject) (RepeatResponseObject, error)

	// (DELETE /api/v1/secure/auth/refresh-token)
	DeleteJWTRefreshToken(ctx context.Context, request DeleteJWTRefreshTokenRequestObject) (DeleteJWTRefreshTokenResponseObject, error)

	// (POST /api/v1/secure/auth/refresh-token)
	CreateJWTRefreshToken(ctx context.Context, request CreateJWTRefreshTokenRequestObject) (CreateJWTRefreshTokenResponseObject, error)

	// (DELETE /api/v1/secure/auth/token)
	DeleteJWTToken(ctx context.Context, request DeleteJWTTokenRequestObject) (DeleteJWTTokenResponseObject, error)

	// (GET /api/v1/secure/cashbunny/accounts)
	GetCashbunnyAccounts(ctx context.Context, request GetCashbunnyAccountsRequestObject) (GetCashbunnyAccountsResponseObject, error)

	// (POST /api/v1/secure/cashbunny/accounts)
	CreateCashbunnyAccount(ctx context.Context, request CreateCashbunnyAccountRequestObject) (CreateCashbunnyAccountResponseObject, error)

	// (DELETE /api/v1/secure/cashbunny/accounts/{accountId})
	DeleteCashbunnyAccount(ctx context.Context, request DeleteCashbunnyAccountRequestObject) (DeleteCashbunnyAccountResponseObject, error)

	// (PUT /api/v1/secure/cashbunny/accounts/{accountId})
	UpdateCashbunnyAccount(ctx context.Context, request UpdateCashbunnyAccountRequestObject) (UpdateCashbunnyAccountResponseObject, error)

	// (GET /api/v1/secure/cashbunny/currencies)
	GetCashbunnySupportedCurrencies(ctx context.Context, request GetCashbunnySupportedCurrenciesRequestObject) (GetCashbunnySupportedCurrenciesResponseObject, error)

	// (GET /api/v1/secure/cashbunny/overview)
	GetCashbunnyOverview(ctx context.Context, request GetCashbunnyOverviewRequestObject) (GetCashbunnyOverviewResponseObject, error)

	// (GET /api/v1/secure/cashbunny/user-preferences)
	GetCashbunnyUserPreference(ctx context.Context, request GetCashbunnyUserPreferenceRequestObject) (GetCashbunnyUserPreferenceResponseObject, error)

	// (POST /api/v1/secure/cashbunny/user-preferences)
	CreateCashbunnyDefaultUserPreference(ctx context.Context, request CreateCashbunnyDefaultUserPreferenceRequestObject) (CreateCashbunnyDefaultUserPreferenceResponseObject, error)

	// (GET /api/v1/secure/system-preferences)
	GetUserSystemPreference(ctx context.Context, request GetUserSystemPreferenceRequestObject) (GetUserSystemPreferenceResponseObject, error)

	// (POST /api/v1/secure/system-preferences)
	CreateDefaultUserSystemPreference(ctx context.Context, request CreateDefaultUserSystemPreferenceRequestObject) (CreateDefaultUserSystemPreferenceResponseObject, error)

	// (PUT /api/v1/secure/system-preferences)
	UpdateUserSystemPreference(ctx context.Context, request UpdateUserSystemPreferenceRequestObject) (UpdateUserSystemPreferenceResponseObject, error)

	// (GET /api/v1/secure/user)
	GetUser(ctx context.Context, request GetUserRequestObject) (GetUserResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// CreateUser operation middleware
func (sh *strictHandler) CreateUser(ctx echo.Context) error {
	var request CreateUserRequestObject

	var body CreateUserJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateUser(ctx.Request().Context(), request.(CreateUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateUserResponseObject); ok {
		return validResponse.VisitCreateUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateJWTToken operation middleware
func (sh *strictHandler) CreateJWTToken(ctx echo.Context) error {
	var request CreateJWTTokenRequestObject

	var body CreateJWTTokenJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateJWTToken(ctx.Request().Context(), request.(CreateJWTTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateJWTToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateJWTTokenResponseObject); ok {
		return validResponse.VisitCreateJWTTokenResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RefreshJWTToken operation middleware
func (sh *strictHandler) RefreshJWTToken(ctx echo.Context) error {
	var request RefreshJWTTokenRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshJWTToken(ctx.Request().Context(), request.(RefreshJWTTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshJWTToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RefreshJWTTokenResponseObject); ok {
		return validResponse.VisitRefreshJWTTokenResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Ping operation middleware
func (sh *strictHandler) Ping(ctx echo.Context) error {
	var request PingRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Ping(ctx.Request().Context(), request.(PingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Ping")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PingResponseObject); ok {
		return validResponse.VisitPingResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Repeat operation middleware
func (sh *strictHandler) Repeat(ctx echo.Context) error {
	var request RepeatRequestObject

	var body RepeatJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Repeat(ctx.Request().Context(), request.(RepeatRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Repeat")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RepeatResponseObject); ok {
		return validResponse.VisitRepeatResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteJWTRefreshToken operation middleware
func (sh *strictHandler) DeleteJWTRefreshToken(ctx echo.Context) error {
	var request DeleteJWTRefreshTokenRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteJWTRefreshToken(ctx.Request().Context(), request.(DeleteJWTRefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteJWTRefreshToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteJWTRefreshTokenResponseObject); ok {
		return validResponse.VisitDeleteJWTRefreshTokenResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateJWTRefreshToken operation middleware
func (sh *strictHandler) CreateJWTRefreshToken(ctx echo.Context) error {
	var request CreateJWTRefreshTokenRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateJWTRefreshToken(ctx.Request().Context(), request.(CreateJWTRefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateJWTRefreshToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateJWTRefreshTokenResponseObject); ok {
		return validResponse.VisitCreateJWTRefreshTokenResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteJWTToken operation middleware
func (sh *strictHandler) DeleteJWTToken(ctx echo.Context) error {
	var request DeleteJWTTokenRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteJWTToken(ctx.Request().Context(), request.(DeleteJWTTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteJWTToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteJWTTokenResponseObject); ok {
		return validResponse.VisitDeleteJWTTokenResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCashbunnyAccounts operation middleware
func (sh *strictHandler) GetCashbunnyAccounts(ctx echo.Context) error {
	var request GetCashbunnyAccountsRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCashbunnyAccounts(ctx.Request().Context(), request.(GetCashbunnyAccountsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCashbunnyAccounts")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCashbunnyAccountsResponseObject); ok {
		return validResponse.VisitGetCashbunnyAccountsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateCashbunnyAccount operation middleware
func (sh *strictHandler) CreateCashbunnyAccount(ctx echo.Context) error {
	var request CreateCashbunnyAccountRequestObject

	var body CreateCashbunnyAccountJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCashbunnyAccount(ctx.Request().Context(), request.(CreateCashbunnyAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCashbunnyAccount")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateCashbunnyAccountResponseObject); ok {
		return validResponse.VisitCreateCashbunnyAccountResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteCashbunnyAccount operation middleware
func (sh *strictHandler) DeleteCashbunnyAccount(ctx echo.Context, accountId uint32) error {
	var request DeleteCashbunnyAccountRequestObject

	request.AccountId = accountId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteCashbunnyAccount(ctx.Request().Context(), request.(DeleteCashbunnyAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteCashbunnyAccount")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteCashbunnyAccountResponseObject); ok {
		return validResponse.VisitDeleteCashbunnyAccountResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateCashbunnyAccount operation middleware
func (sh *strictHandler) UpdateCashbunnyAccount(ctx echo.Context, accountId uint32) error {
	var request UpdateCashbunnyAccountRequestObject

	request.AccountId = accountId

	var body UpdateCashbunnyAccountJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateCashbunnyAccount(ctx.Request().Context(), request.(UpdateCashbunnyAccountRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateCashbunnyAccount")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateCashbunnyAccountResponseObject); ok {
		return validResponse.VisitUpdateCashbunnyAccountResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCashbunnySupportedCurrencies operation middleware
func (sh *strictHandler) GetCashbunnySupportedCurrencies(ctx echo.Context) error {
	var request GetCashbunnySupportedCurrenciesRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCashbunnySupportedCurrencies(ctx.Request().Context(), request.(GetCashbunnySupportedCurrenciesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCashbunnySupportedCurrencies")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCashbunnySupportedCurrenciesResponseObject); ok {
		return validResponse.VisitGetCashbunnySupportedCurrenciesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCashbunnyOverview operation middleware
func (sh *strictHandler) GetCashbunnyOverview(ctx echo.Context, params GetCashbunnyOverviewParams) error {
	var request GetCashbunnyOverviewRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCashbunnyOverview(ctx.Request().Context(), request.(GetCashbunnyOverviewRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCashbunnyOverview")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCashbunnyOverviewResponseObject); ok {
		return validResponse.VisitGetCashbunnyOverviewResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCashbunnyUserPreference operation middleware
func (sh *strictHandler) GetCashbunnyUserPreference(ctx echo.Context) error {
	var request GetCashbunnyUserPreferenceRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCashbunnyUserPreference(ctx.Request().Context(), request.(GetCashbunnyUserPreferenceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCashbunnyUserPreference")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCashbunnyUserPreferenceResponseObject); ok {
		return validResponse.VisitGetCashbunnyUserPreferenceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateCashbunnyDefaultUserPreference operation middleware
func (sh *strictHandler) CreateCashbunnyDefaultUserPreference(ctx echo.Context) error {
	var request CreateCashbunnyDefaultUserPreferenceRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCashbunnyDefaultUserPreference(ctx.Request().Context(), request.(CreateCashbunnyDefaultUserPreferenceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCashbunnyDefaultUserPreference")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateCashbunnyDefaultUserPreferenceResponseObject); ok {
		return validResponse.VisitCreateCashbunnyDefaultUserPreferenceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetUserSystemPreference operation middleware
func (sh *strictHandler) GetUserSystemPreference(ctx echo.Context) error {
	var request GetUserSystemPreferenceRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUserSystemPreference(ctx.Request().Context(), request.(GetUserSystemPreferenceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUserSystemPreference")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetUserSystemPreferenceResponseObject); ok {
		return validResponse.VisitGetUserSystemPreferenceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateDefaultUserSystemPreference operation middleware
func (sh *strictHandler) CreateDefaultUserSystemPreference(ctx echo.Context) error {
	var request CreateDefaultUserSystemPreferenceRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDefaultUserSystemPreference(ctx.Request().Context(), request.(CreateDefaultUserSystemPreferenceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDefaultUserSystemPreference")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateDefaultUserSystemPreferenceResponseObject); ok {
		return validResponse.VisitCreateDefaultUserSystemPreferenceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateUserSystemPreference operation middleware
func (sh *strictHandler) UpdateUserSystemPreference(ctx echo.Context) error {
	var request UpdateUserSystemPreferenceRequestObject

	var body UpdateUserSystemPreferenceJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateUserSystemPreference(ctx.Request().Context(), request.(UpdateUserSystemPreferenceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateUserSystemPreference")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateUserSystemPreferenceResponseObject); ok {
		return validResponse.VisitUpdateUserSystemPreferenceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetUser operation middleware
func (sh *strictHandler) GetUser(ctx echo.Context) error {
	var request GetUserRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUser(ctx.Request().Context(), request.(GetUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetUserResponseObject); ok {
		return validResponse.VisitGetUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xae28buRH/KnPbAtcCa8uPpC0EBGjOd+nFRVvDdhAUgSFQy5HEmEtuSK5s1dB3L0ju",
	"rvbB1cOWnRxy/xjyLjkczszvxxnuPESJTDMpUBgdDR8incwwJe5nQvRsnAuxeJskMhfGPqOoE8Uyw6SI",
	"htG/JEUOCjOFGoVhYgpELGDCBBEJIxyInwk6T2ZANIyJuC0fxpAopMxAQhSN4Y5wjgbQJIdRHGVKZqgM",
	"Q6cJScv1J1KlxETDiMp8zDGKI5FzTuzPoVE5xpFZZBgNI5GnY1TRMi4mjyjTGScLK6RnijaKiamdkhCD",
	"U6nc4O5LhcQgHRETfp0rhSIJz22YL/Ce0cYmcybM6UlUaciEwanflSApBkVIRVGNmKB4v60s/yQgK89o",
	"/1aXcaTwS84U0mj4yapeM1yhYHPHNeMUizbVbdi2sfpNpbYcf8bEeCcV4fmfOao5w7tufJZvQE4g16h+",
	"1DDO6RQN3CJmTEwDoaY1mlERou4JM5i6H39UOImG0R8GK8QMCrgMOlipzBoRpcjC/j9RMl2joyHKaqYN",
	"UQYMc9breIQzMmacmcXzqCjQjO6kMjNnCkqZVZLwi4aJ1kd19G804GRAhgraHq97MFNywsyIS61HOk9T",
	"4hHXt27TUXifodDhuPWCg68UzlHkuDmey4FxtVIlNxSNTRt88MHmxw/sBqHYINwxM2MCzAydkyeK1D29",
	"Emjk5lhBQXsjxSgiNEnszEfEyPVqdihO6sJHNq5HVgLNOdI9r9XyisOQM049WMOhFLfBHIRPy1Lr97aW",
	"hy6xCHa8zDludVqyM8JRUKJAVZNB5RzhTzNjMj0cDCgxxCiS3KI6ZGgmh1JNB1Qmg5lJ+UBNktevX73+",
	"c4fHqhO7S/fUOI4JwmOi8Ev4ZBIG1ZzwsMhcGMY3Y8pJXykQF1rWpJei1hr6qvRHPXK2Sk6gciXU3LxT",
	"vrFFfvGiKQNFbZgg9n0Z1KPt04jQ7N7UYnuxq2geqQILW1FBC0LLONIyVwk+Ymetib2b2jnHaWY0Rag0",
	"UptWRPSnNV1DhTYc3kuv59c4dS2qHgEmJqYcgRiZsqSW9degBWM0d4gCanz7O9b2irWK0kam6cGtEBfk",
	"0pfAXalsv6teAplNLdYh9Tlx2efEtXi1OeaFwgk6+uiDLMUJExauRf1zVk6HrJqrq/qc4oTk3FRZe7gc",
	"t6JGxZDiUZXxdf28Lp1rSwptGJWSqru9X+xjSCRFIIJCLigqvrA7dRO6RJOi1mQaMNRba5tJzqEYAf71",
	"2MqyabpXwNYBJM3sYRaZGSqEO/tHyxRtnj/mmGqX3Ls5NmuDhcztqzmjSEMp+pxwRn04FEvrnequSqGH",
	"yKoxmjDk1KsHHMXUzCDNtYExVjR87Ix1clTzTGnplmtKc4XVDDnKOrNbp23g4+2JhcvpFOmIiT5RPVQT",
	"YooCdQ2RDfD37e9qoQ2mO8IOtJsVRBwnYpqTKcaukIP/SYFh0JUDfe1bRuJncnB+0X8LVrNB19va5h7M",
	"uCMg9YuMkShUb3N/AeD/e1f65vzjdcFU1s7F25WrbMESLZeuVpi44tUw45T81WLkHRKTK4QrVHNUcPnL",
	"1TW8vXhv4wuV9rY7Pjw6dKEpMxQkY9EwOj08Ojy1xiBm5lQckIwN5scDUiiZSR24mTxzrtRAQOCdd0Ku",
	"S39Y78eAKWHcwSEjWt9JZQPDWtyF+ntaSbFEG/kgQm1+knThCyxh0CcuJMs4S9y0wWftD19/0AauLeyq",
	"XX1LnBJwaPPKNTkHtbHK/714dJj4Srjh6Di6P5AkYweWF6coDvDeKHJgyNQtXiDZTvALWG9Vu+9VqiSP",
	"v4GR8NcTSGZE2TNT6djZz5qCMAEEOBqDKgafsbmXBHSGLi2spnX2NSp1GB2fnP7whF1VgtzOSl9v3tmp",
	"3dnrIyA8mxGRp6hYUtdYB13xBEXLheKUiTencUru37w+8uipk1UZBtVOau7qUlRztiUC90BnUmgffSdH",
	"J4FbpX9ayL06OtoprNdll/7EdPo0l/qJULj0OLKvl3EDzgMjb1H0g/oSTa5ECerzj9dwbSfARCogUHgk",
	"hODzj9du5N5QXMfMmlAOHfqbg7I3CGOfX6TknqV5auO1egflTcozRWlPfO4vLo+CcRlHMyTU4m/4EF2h",
	"OTiT8pZh0zXNWT4kVmPBS+i6wqn18lFv1zx9/jXtoQVMA2Xa5gXUj8nyIKwmCvUMtctcfTZuVvDqYKoY",
	"3wDV1/dlLaGJhp+aqcynm+VNnWwyO2n4EE3RhMqBRIo5CuYuY1HQTDJh7AGRzDC5dWyTSCGwvDtsWufC",
	"QyxkkkeSTW/hciHF9IcG5ssn61PgUmAYqd3DoUHUCjP0Cfh6kraxpG0gFavFznDGlcBTyHKVSWudbnA5",
	"8fsi6l7bXdmctCz4bKF2R7yTx4XaY5LcNmz7K3Iun2rcrWhw33u9njW3ave3/61tiBsHTvTnvPIMclCd",
	"9xQ5mlAxRW5LWuLMesUPtE+YAm2kQpt+Om4YL0CjcdGF9xlTdqIEYrN7A+5Aa8faz07Y+cfrgtF66OzV",
	"N0ln8dZJUrG7HZKl9fb4akf11zk2dzhX6jH+rcT2byqou7asrjsH9YaH4MF9iUYxnNuqn/PaRWc50dna",
	"XQXMSPfg+Qeas1aHhN7vOf4MHRstgq5W2JqhH88yiVRUA6m+7AATUCncQy1tA+/tmK83bLUugoo3ICfO",
	"/4W2h0+oikqLx1KgnLxxTQYaytYChhqK3hENReuIdpauf3panb3nF//dhy6jyvajap3lpk9aj1jHVoIW",
	"BsvahWur/4ek2LK2JStN5riPjVoFjgsFWr1urfi2L0tFlIvXIr/LOEmQArO02L157rlKrW6iW5gryt9a",
	"51tPy9s+6+Kvc1+zD/YePBS/3tPlutPRn1969ZU5afN5z5EX4JiMKJKiu8azejMrPyOub8iHcFTpFLU9",
	"EtdMuPkrxfJmWwduw7yhYv2D+ya5PfH68d+AUfZB87+T2a5k1vLFI1Qsmy96eK9JdvU9fN981/w83pev",
	"ukqtAuePGnSeZVIZm/mvBKxLVa/KCWf18XvMWld6jIigo6kimf8AuMOH6vVfmvtW2FsSu85PstY8vp2X",
	"QNa6ysuSYtVZnnEiRKC4rjut6ljv0HBfv2/ZKWxDxDWIF0Wfo+0vOa5a7odlj2yAopkwf3kVYuh4q5VR",
	"0HXruqbcXVa9eWKgblU7VbZ+juixrj+ofdbfGEWu/Kz3AUykWoXW2qBp9fvsFeSuDydrdDVsZdyWTsH2",
	"nprYbRFt2T5wQfGhaTxbxoOQBsaIAormDVigeUJd6+vUqg9qBfqW4zYVuD97Ad+Rzx6BI98Wszt+Ou00",
	"Idx8CHXr7N8BXpcd/BDsIgo6oSt6H/jpGO8FYLQdeGqY+V4d97SqcKOd/bBeAz+uRHuEzZ75Q9hv2L9d",
	"kiy7KtfSoitPczNDYayRkPpQcI14Pdy4f0htY+CgQfdoPjdCzcPp9DupoF79RnGUK160LurhYMBlQvhM",
	"ajM8Pj05jZY3y/8HAAD//xsRZJEfPQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
