// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /api/v1/auth)
	CreateUser(ctx echo.Context) error

	// (POST /api/v1/auth/token)
	CreateJWTToken(ctx echo.Context) error

	// (PUT /api/v1/auth/token)
	RefreshJWTToken(ctx echo.Context) error

	// (GET /api/v1/ping)
	Ping(ctx echo.Context) error

	// (POST /api/v1/repeat)
	Repeat(ctx echo.Context) error

	// (DELETE /api/v1/secure/auth/refresh_token)
	DeleteJWTRefreshToken(ctx echo.Context) error

	// (POST /api/v1/secure/auth/refresh_token)
	CreateJWTRefreshToken(ctx echo.Context) error

	// (DELETE /api/v1/secure/auth/token)
	DeleteJWTToken(ctx echo.Context) error

	// (GET /api/v1/secure/cashbunny/currencies)
	GetCashbunnySupportedCurrencies(ctx echo.Context) error

	// (GET /api/v1/secure/cashbunny/overview)
	GetCashbunnyOverview(ctx echo.Context, params GetCashbunnyOverviewParams) error

	// (GET /api/v1/secure/cashbunny/user_preferences)
	GetCashbunnyUserPreference(ctx echo.Context) error

	// (POST /api/v1/secure/cashbunny/user_preferences)
	CreateCashbunnyDefaultUserPreference(ctx echo.Context) error

	// (GET /api/v1/secure/system_preferences)
	GetUserSystemPreference(ctx echo.Context) error

	// (POST /api/v1/secure/system_preferences)
	CreateDefaultUserSystemPreference(ctx echo.Context) error

	// (PUT /api/v1/secure/system_preferences)
	UpdateUserSystemPreference(ctx echo.Context) error

	// (GET /api/v1/secure/user)
	GetUser(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// CreateUser converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateUser(ctx)
	return err
}

// CreateJWTToken converts echo context to params.
func (w *ServerInterfaceWrapper) CreateJWTToken(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateJWTToken(ctx)
	return err
}

// RefreshJWTToken converts echo context to params.
func (w *ServerInterfaceWrapper) RefreshJWTToken(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RefreshJWTToken(ctx)
	return err
}

// Ping converts echo context to params.
func (w *ServerInterfaceWrapper) Ping(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Ping(ctx)
	return err
}

// Repeat converts echo context to params.
func (w *ServerInterfaceWrapper) Repeat(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Repeat(ctx)
	return err
}

// DeleteJWTRefreshToken converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteJWTRefreshToken(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteJWTRefreshToken(ctx)
	return err
}

// CreateJWTRefreshToken converts echo context to params.
func (w *ServerInterfaceWrapper) CreateJWTRefreshToken(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateJWTRefreshToken(ctx)
	return err
}

// DeleteJWTToken converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteJWTToken(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteJWTToken(ctx)
	return err
}

// GetCashbunnySupportedCurrencies converts echo context to params.
func (w *ServerInterfaceWrapper) GetCashbunnySupportedCurrencies(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCashbunnySupportedCurrencies(ctx)
	return err
}

// GetCashbunnyOverview converts echo context to params.
func (w *ServerInterfaceWrapper) GetCashbunnyOverview(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCashbunnyOverviewParams
	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameter("form", true, false, "from", ctx.QueryParams(), &params.From)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter from: %s", err))
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameter("form", true, false, "to", ctx.QueryParams(), &params.To)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter to: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCashbunnyOverview(ctx, params)
	return err
}

// GetCashbunnyUserPreference converts echo context to params.
func (w *ServerInterfaceWrapper) GetCashbunnyUserPreference(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCashbunnyUserPreference(ctx)
	return err
}

// CreateCashbunnyDefaultUserPreference converts echo context to params.
func (w *ServerInterfaceWrapper) CreateCashbunnyDefaultUserPreference(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateCashbunnyDefaultUserPreference(ctx)
	return err
}

// GetUserSystemPreference converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserSystemPreference(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserSystemPreference(ctx)
	return err
}

// CreateDefaultUserSystemPreference converts echo context to params.
func (w *ServerInterfaceWrapper) CreateDefaultUserSystemPreference(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateDefaultUserSystemPreference(ctx)
	return err
}

// UpdateUserSystemPreference converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateUserSystemPreference(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateUserSystemPreference(ctx)
	return err
}

// GetUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetUser(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUser(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/api/v1/auth", wrapper.CreateUser)
	router.POST(baseURL+"/api/v1/auth/token", wrapper.CreateJWTToken)
	router.PUT(baseURL+"/api/v1/auth/token", wrapper.RefreshJWTToken)
	router.GET(baseURL+"/api/v1/ping", wrapper.Ping)
	router.POST(baseURL+"/api/v1/repeat", wrapper.Repeat)
	router.DELETE(baseURL+"/api/v1/secure/auth/refresh_token", wrapper.DeleteJWTRefreshToken)
	router.POST(baseURL+"/api/v1/secure/auth/refresh_token", wrapper.CreateJWTRefreshToken)
	router.DELETE(baseURL+"/api/v1/secure/auth/token", wrapper.DeleteJWTToken)
	router.GET(baseURL+"/api/v1/secure/cashbunny/currencies", wrapper.GetCashbunnySupportedCurrencies)
	router.GET(baseURL+"/api/v1/secure/cashbunny/overview", wrapper.GetCashbunnyOverview)
	router.GET(baseURL+"/api/v1/secure/cashbunny/user_preferences", wrapper.GetCashbunnyUserPreference)
	router.POST(baseURL+"/api/v1/secure/cashbunny/user_preferences", wrapper.CreateCashbunnyDefaultUserPreference)
	router.GET(baseURL+"/api/v1/secure/system_preferences", wrapper.GetUserSystemPreference)
	router.POST(baseURL+"/api/v1/secure/system_preferences", wrapper.CreateDefaultUserSystemPreference)
	router.PUT(baseURL+"/api/v1/secure/system_preferences", wrapper.UpdateUserSystemPreference)
	router.GET(baseURL+"/api/v1/secure/user", wrapper.GetUser)

}

type CreateUserRequestObject struct {
	Body *CreateUserJSONRequestBody
}

type CreateUserResponseObject interface {
	VisitCreateUserResponse(w http.ResponseWriter) error
}

type CreateUser202Response struct {
}

func (response CreateUser202Response) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type CreateUser400JSONResponse Error

func (response CreateUser400JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateJWTTokenRequestObject struct {
	Body *CreateJWTTokenJSONRequestBody
}

type CreateJWTTokenResponseObject interface {
	VisitCreateJWTTokenResponse(w http.ResponseWriter) error
}

type CreateJWTToken200ResponseHeaders struct {
	SetCookie string
}

type CreateJWTToken200Response struct {
	Headers CreateJWTToken200ResponseHeaders
}

func (response CreateJWTToken200Response) VisitCreateJWTTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)
	return nil
}

type CreateJWTToken400JSONResponse Error

func (response CreateJWTToken400JSONResponse) VisitCreateJWTTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateJWTToken403JSONResponse Error

func (response CreateJWTToken403JSONResponse) VisitCreateJWTTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type RefreshJWTTokenRequestObject struct {
}

type RefreshJWTTokenResponseObject interface {
	VisitRefreshJWTTokenResponse(w http.ResponseWriter) error
}

type RefreshJWTToken200ResponseHeaders struct {
	SetCookie string
}

type RefreshJWTToken200Response struct {
	Headers RefreshJWTToken200ResponseHeaders
}

func (response RefreshJWTToken200Response) VisitRefreshJWTTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)
	return nil
}

type PingRequestObject struct {
}

type PingResponseObject interface {
	VisitPingResponse(w http.ResponseWriter) error
}

type Ping200JSONResponse struct {
	// Message Pong!
	Message string `json:"message"`
}

func (response Ping200JSONResponse) VisitPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RepeatRequestObject struct {
	Body *RepeatJSONRequestBody
}

type RepeatResponseObject interface {
	VisitRepeatResponse(w http.ResponseWriter) error
}

type Repeat200JSONResponse struct {
	// Message The message you sent
	Message string `json:"message"`
}

func (response Repeat200JSONResponse) VisitRepeatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteJWTRefreshTokenRequestObject struct {
}

type DeleteJWTRefreshTokenResponseObject interface {
	VisitDeleteJWTRefreshTokenResponse(w http.ResponseWriter) error
}

type DeleteJWTRefreshToken204ResponseHeaders struct {
	SetCookie string
}

type DeleteJWTRefreshToken204Response struct {
	Headers DeleteJWTRefreshToken204ResponseHeaders
}

func (response DeleteJWTRefreshToken204Response) VisitDeleteJWTRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(204)
	return nil
}

type CreateJWTRefreshTokenRequestObject struct {
}

type CreateJWTRefreshTokenResponseObject interface {
	VisitCreateJWTRefreshTokenResponse(w http.ResponseWriter) error
}

type CreateJWTRefreshToken200ResponseHeaders struct {
	SetCookie string
}

type CreateJWTRefreshToken200Response struct {
	Headers CreateJWTRefreshToken200ResponseHeaders
}

func (response CreateJWTRefreshToken200Response) VisitCreateJWTRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)
	return nil
}

type CreateJWTRefreshToken403JSONResponse Error

func (response CreateJWTRefreshToken403JSONResponse) VisitCreateJWTRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteJWTTokenRequestObject struct {
}

type DeleteJWTTokenResponseObject interface {
	VisitDeleteJWTTokenResponse(w http.ResponseWriter) error
}

type DeleteJWTToken204ResponseHeaders struct {
	SetCookie string
}

type DeleteJWTToken204Response struct {
	Headers DeleteJWTToken204ResponseHeaders
}

func (response DeleteJWTToken204Response) VisitDeleteJWTTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(204)
	return nil
}

type GetCashbunnySupportedCurrenciesRequestObject struct {
}

type GetCashbunnySupportedCurrenciesResponseObject interface {
	VisitGetCashbunnySupportedCurrenciesResponse(w http.ResponseWriter) error
}

type GetCashbunnySupportedCurrencies200JSONResponse struct {
	CurrenciesAndGrapheme map[string]string `json:"currencies_and_grapheme"`
}

func (response GetCashbunnySupportedCurrencies200JSONResponse) VisitGetCashbunnySupportedCurrenciesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCashbunnyOverviewRequestObject struct {
	Params GetCashbunnyOverviewParams
}

type GetCashbunnyOverviewResponseObject interface {
	VisitGetCashbunnyOverviewResponse(w http.ResponseWriter) error
}

type GetCashbunnyOverview200JSONResponse CashbunnyOverview

func (response GetCashbunnyOverview200JSONResponse) VisitGetCashbunnyOverviewResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCashbunnyUserPreferenceRequestObject struct {
}

type GetCashbunnyUserPreferenceResponseObject interface {
	VisitGetCashbunnyUserPreferenceResponse(w http.ResponseWriter) error
}

type GetCashbunnyUserPreference200JSONResponse struct {
	// UserPreference Model defining user's Cashbunny preferences such as default currency etc.
	UserPreference CashbunnyUserPreference `json:"user_preference"`
}

func (response GetCashbunnyUserPreference200JSONResponse) VisitGetCashbunnyUserPreferenceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCashbunnyUserPreference404Response struct {
}

func (response GetCashbunnyUserPreference404Response) VisitGetCashbunnyUserPreferenceResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type CreateCashbunnyDefaultUserPreferenceRequestObject struct {
}

type CreateCashbunnyDefaultUserPreferenceResponseObject interface {
	VisitCreateCashbunnyDefaultUserPreferenceResponse(w http.ResponseWriter) error
}

type CreateCashbunnyDefaultUserPreference200JSONResponse struct {
	// UserPreference Model defining user's Cashbunny preferences such as default currency etc.
	UserPreference CashbunnyUserPreference `json:"user_preference"`
}

func (response CreateCashbunnyDefaultUserPreference200JSONResponse) VisitCreateCashbunnyDefaultUserPreferenceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUserSystemPreferenceRequestObject struct {
}

type GetUserSystemPreferenceResponseObject interface {
	VisitGetUserSystemPreferenceResponse(w http.ResponseWriter) error
}

type GetUserSystemPreference200JSONResponse struct {
	// UserSystemPreference Model defining user system preferences such as language, time zone etc.
	UserSystemPreference UserSystemPreference `json:"user_system_preference"`
}

func (response GetUserSystemPreference200JSONResponse) VisitGetUserSystemPreferenceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUserSystemPreference404Response struct {
}

func (response GetUserSystemPreference404Response) VisitGetUserSystemPreferenceResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type CreateDefaultUserSystemPreferenceRequestObject struct {
}

type CreateDefaultUserSystemPreferenceResponseObject interface {
	VisitCreateDefaultUserSystemPreferenceResponse(w http.ResponseWriter) error
}

type CreateDefaultUserSystemPreference200JSONResponse struct {
	// UserSystemPreference Model defining user system preferences such as language, time zone etc.
	UserSystemPreference UserSystemPreference `json:"user_system_preference"`
}

func (response CreateDefaultUserSystemPreference200JSONResponse) VisitCreateDefaultUserSystemPreferenceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateUserSystemPreferenceRequestObject struct {
	Body *UpdateUserSystemPreferenceJSONRequestBody
}

type UpdateUserSystemPreferenceResponseObject interface {
	VisitUpdateUserSystemPreferenceResponse(w http.ResponseWriter) error
}

type UpdateUserSystemPreference200JSONResponse struct {
	// UserSystemPreference Model defining user system preferences such as language, time zone etc.
	UserSystemPreference UserSystemPreference `json:"user_system_preference"`
}

func (response UpdateUserSystemPreference200JSONResponse) VisitUpdateUserSystemPreferenceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUserRequestObject struct {
}

type GetUserResponseObject interface {
	VisitGetUserResponse(w http.ResponseWriter) error
}

type GetUser200JSONResponse struct {
	User User `json:"user"`
}

func (response GetUser200JSONResponse) VisitGetUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /api/v1/auth)
	CreateUser(ctx context.Context, request CreateUserRequestObject) (CreateUserResponseObject, error)

	// (POST /api/v1/auth/token)
	CreateJWTToken(ctx context.Context, request CreateJWTTokenRequestObject) (CreateJWTTokenResponseObject, error)

	// (PUT /api/v1/auth/token)
	RefreshJWTToken(ctx context.Context, request RefreshJWTTokenRequestObject) (RefreshJWTTokenResponseObject, error)

	// (GET /api/v1/ping)
	Ping(ctx context.Context, request PingRequestObject) (PingResponseObject, error)

	// (POST /api/v1/repeat)
	Repeat(ctx context.Context, request RepeatRequestObject) (RepeatResponseObject, error)

	// (DELETE /api/v1/secure/auth/refresh_token)
	DeleteJWTRefreshToken(ctx context.Context, request DeleteJWTRefreshTokenRequestObject) (DeleteJWTRefreshTokenResponseObject, error)

	// (POST /api/v1/secure/auth/refresh_token)
	CreateJWTRefreshToken(ctx context.Context, request CreateJWTRefreshTokenRequestObject) (CreateJWTRefreshTokenResponseObject, error)

	// (DELETE /api/v1/secure/auth/token)
	DeleteJWTToken(ctx context.Context, request DeleteJWTTokenRequestObject) (DeleteJWTTokenResponseObject, error)

	// (GET /api/v1/secure/cashbunny/currencies)
	GetCashbunnySupportedCurrencies(ctx context.Context, request GetCashbunnySupportedCurrenciesRequestObject) (GetCashbunnySupportedCurrenciesResponseObject, error)

	// (GET /api/v1/secure/cashbunny/overview)
	GetCashbunnyOverview(ctx context.Context, request GetCashbunnyOverviewRequestObject) (GetCashbunnyOverviewResponseObject, error)

	// (GET /api/v1/secure/cashbunny/user_preferences)
	GetCashbunnyUserPreference(ctx context.Context, request GetCashbunnyUserPreferenceRequestObject) (GetCashbunnyUserPreferenceResponseObject, error)

	// (POST /api/v1/secure/cashbunny/user_preferences)
	CreateCashbunnyDefaultUserPreference(ctx context.Context, request CreateCashbunnyDefaultUserPreferenceRequestObject) (CreateCashbunnyDefaultUserPreferenceResponseObject, error)

	// (GET /api/v1/secure/system_preferences)
	GetUserSystemPreference(ctx context.Context, request GetUserSystemPreferenceRequestObject) (GetUserSystemPreferenceResponseObject, error)

	// (POST /api/v1/secure/system_preferences)
	CreateDefaultUserSystemPreference(ctx context.Context, request CreateDefaultUserSystemPreferenceRequestObject) (CreateDefaultUserSystemPreferenceResponseObject, error)

	// (PUT /api/v1/secure/system_preferences)
	UpdateUserSystemPreference(ctx context.Context, request UpdateUserSystemPreferenceRequestObject) (UpdateUserSystemPreferenceResponseObject, error)

	// (GET /api/v1/secure/user)
	GetUser(ctx context.Context, request GetUserRequestObject) (GetUserResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// CreateUser operation middleware
func (sh *strictHandler) CreateUser(ctx echo.Context) error {
	var request CreateUserRequestObject

	var body CreateUserJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateUser(ctx.Request().Context(), request.(CreateUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateUserResponseObject); ok {
		return validResponse.VisitCreateUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateJWTToken operation middleware
func (sh *strictHandler) CreateJWTToken(ctx echo.Context) error {
	var request CreateJWTTokenRequestObject

	var body CreateJWTTokenJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateJWTToken(ctx.Request().Context(), request.(CreateJWTTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateJWTToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateJWTTokenResponseObject); ok {
		return validResponse.VisitCreateJWTTokenResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RefreshJWTToken operation middleware
func (sh *strictHandler) RefreshJWTToken(ctx echo.Context) error {
	var request RefreshJWTTokenRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshJWTToken(ctx.Request().Context(), request.(RefreshJWTTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshJWTToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RefreshJWTTokenResponseObject); ok {
		return validResponse.VisitRefreshJWTTokenResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Ping operation middleware
func (sh *strictHandler) Ping(ctx echo.Context) error {
	var request PingRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Ping(ctx.Request().Context(), request.(PingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Ping")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PingResponseObject); ok {
		return validResponse.VisitPingResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Repeat operation middleware
func (sh *strictHandler) Repeat(ctx echo.Context) error {
	var request RepeatRequestObject

	var body RepeatJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Repeat(ctx.Request().Context(), request.(RepeatRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Repeat")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RepeatResponseObject); ok {
		return validResponse.VisitRepeatResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteJWTRefreshToken operation middleware
func (sh *strictHandler) DeleteJWTRefreshToken(ctx echo.Context) error {
	var request DeleteJWTRefreshTokenRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteJWTRefreshToken(ctx.Request().Context(), request.(DeleteJWTRefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteJWTRefreshToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteJWTRefreshTokenResponseObject); ok {
		return validResponse.VisitDeleteJWTRefreshTokenResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateJWTRefreshToken operation middleware
func (sh *strictHandler) CreateJWTRefreshToken(ctx echo.Context) error {
	var request CreateJWTRefreshTokenRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateJWTRefreshToken(ctx.Request().Context(), request.(CreateJWTRefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateJWTRefreshToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateJWTRefreshTokenResponseObject); ok {
		return validResponse.VisitCreateJWTRefreshTokenResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteJWTToken operation middleware
func (sh *strictHandler) DeleteJWTToken(ctx echo.Context) error {
	var request DeleteJWTTokenRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteJWTToken(ctx.Request().Context(), request.(DeleteJWTTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteJWTToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteJWTTokenResponseObject); ok {
		return validResponse.VisitDeleteJWTTokenResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCashbunnySupportedCurrencies operation middleware
func (sh *strictHandler) GetCashbunnySupportedCurrencies(ctx echo.Context) error {
	var request GetCashbunnySupportedCurrenciesRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCashbunnySupportedCurrencies(ctx.Request().Context(), request.(GetCashbunnySupportedCurrenciesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCashbunnySupportedCurrencies")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCashbunnySupportedCurrenciesResponseObject); ok {
		return validResponse.VisitGetCashbunnySupportedCurrenciesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCashbunnyOverview operation middleware
func (sh *strictHandler) GetCashbunnyOverview(ctx echo.Context, params GetCashbunnyOverviewParams) error {
	var request GetCashbunnyOverviewRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCashbunnyOverview(ctx.Request().Context(), request.(GetCashbunnyOverviewRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCashbunnyOverview")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCashbunnyOverviewResponseObject); ok {
		return validResponse.VisitGetCashbunnyOverviewResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCashbunnyUserPreference operation middleware
func (sh *strictHandler) GetCashbunnyUserPreference(ctx echo.Context) error {
	var request GetCashbunnyUserPreferenceRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCashbunnyUserPreference(ctx.Request().Context(), request.(GetCashbunnyUserPreferenceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCashbunnyUserPreference")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCashbunnyUserPreferenceResponseObject); ok {
		return validResponse.VisitGetCashbunnyUserPreferenceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateCashbunnyDefaultUserPreference operation middleware
func (sh *strictHandler) CreateCashbunnyDefaultUserPreference(ctx echo.Context) error {
	var request CreateCashbunnyDefaultUserPreferenceRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCashbunnyDefaultUserPreference(ctx.Request().Context(), request.(CreateCashbunnyDefaultUserPreferenceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCashbunnyDefaultUserPreference")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateCashbunnyDefaultUserPreferenceResponseObject); ok {
		return validResponse.VisitCreateCashbunnyDefaultUserPreferenceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetUserSystemPreference operation middleware
func (sh *strictHandler) GetUserSystemPreference(ctx echo.Context) error {
	var request GetUserSystemPreferenceRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUserSystemPreference(ctx.Request().Context(), request.(GetUserSystemPreferenceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUserSystemPreference")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetUserSystemPreferenceResponseObject); ok {
		return validResponse.VisitGetUserSystemPreferenceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateDefaultUserSystemPreference operation middleware
func (sh *strictHandler) CreateDefaultUserSystemPreference(ctx echo.Context) error {
	var request CreateDefaultUserSystemPreferenceRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDefaultUserSystemPreference(ctx.Request().Context(), request.(CreateDefaultUserSystemPreferenceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDefaultUserSystemPreference")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateDefaultUserSystemPreferenceResponseObject); ok {
		return validResponse.VisitCreateDefaultUserSystemPreferenceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateUserSystemPreference operation middleware
func (sh *strictHandler) UpdateUserSystemPreference(ctx echo.Context) error {
	var request UpdateUserSystemPreferenceRequestObject

	var body UpdateUserSystemPreferenceJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateUserSystemPreference(ctx.Request().Context(), request.(UpdateUserSystemPreferenceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateUserSystemPreference")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateUserSystemPreferenceResponseObject); ok {
		return validResponse.VisitUpdateUserSystemPreferenceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetUser operation middleware
func (sh *strictHandler) GetUser(ctx echo.Context) error {
	var request GetUserRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUser(ctx.Request().Context(), request.(GetUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetUserResponseObject); ok {
		return validResponse.VisitGetUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabW/cuBH+Kzy1wLWA7HXspC0WOKC53F3vUrQ1Ygf5EAQLrjirZUyRCjmyvQ3834sh",
	"Ja20ota7ztq5w/WLsZY4w3l5nuGQ1OckM0VpNGh0yfRz4rIlFNz/zLhbziutVy+zzFQa6ZkAl1lZojQ6",
	"mSb/MgIUs1BacKBR6pxxvWILqbnOJFeMB0nmqmzJuGNzrq+ahynLLAiJLONWpOyGKwXIALPjJE1Ka0qw",
	"KMFbwotm/oWxBcdkmghTzRUkaaIrpTj9nKKtIE1wVUIyTXRVzMEmd2ktPBPSlYqvSMmIiEMrdU4iGUfI",
	"jfWDhy8tcAQx4xh/XVkLOovL9sIXeS9Fz8lKajw7TVoLpUbIg1eaFxBVER5EXlSlGLf7Lk0sfKqkBZFM",
	"35MdnSjUs/XN73haT9oLTW++D60HZv4RMgwxrtH1n2uw1xJuhvBq3jCzYJUD+61j80rkgOwKoJQ6jyDF",
	"OcBZjTD/RCIU/scfLSySafKHyRrwkxrtkwHU20Am3Fq+ov8X1hRbbERuyTKH3CJD6eM1yIGSfC6VxNXj",
	"mKgBZzfG4tKHQghJRnJ13gvRdlAm/wZkXgcrwbLNHHczWFqzkDhTxrmZq4qCB8KMzdtPFNyWoF0cqUFx",
	"9JWFa9AV3I/gZmDaztTqjaGxH4O3AWxh/IQcZLWD7EbiUmqGS/BJXljezfRaIZr7sQJajCIFLdeOZyT5",
	"AIxcrqVjOOkqnxGuZ6RBVArEgefayIrnkA9OF6xxKKWbZI7SZyNS233bWofeQA12eFMp2Gmxk6+4Ai24",
	"ZbYVZrZSwP60RCzddDIRHDlanl2BPZaAi2Nj84kw2WSJhZrYRfbixfMXfx7UsXbBHVZ+gb7GROmxsPAp",
	"vrBoBHvNVVxlpVGq+znlta8NSGsrO9obVVsDfdHko4ucnXoL1qaSddK8V7uwQ3vwpCu+AIdSc3rfgHq2",
	"excQkx7tDHZXu0bzzNZc2KkUbFDoLk2cqWwGD/BsQ3DUqb27mn4PU0Ol18xsIGK8rRkGKuZw3JfRzG9J",
	"6lZWPYBMUucKGEdTyKzTtHeoxeaANwCadert/7l2UK61JW2G/QzuxLhoLX0K3jXGjqfqKZjZt2IbUx+T",
	"l2NJ3MpX6jHPLSzAl48xygpYSE10rfc/rxpxVrayrt1eC1jwSmHbtcd306RqVg+pH7Ud38h2cqSd29QU",
	"cxisNXbo3o/0mGVGAONasEoLsGpFnnqBYaEpwDmeRwL1kmKzqBSrR7Dwek66qE0PBtA+gBclLWYJLsEC",
	"u6E/zhRAff5cQeF8c+9lqGtjK1PRq2spQMRa9GuupAhwqKd2e+27WoM+J2TGbCFBiWAeU6BzXLKicsjm",
	"0JbhZz5YpyedzDSR3khNE664mbFEUTKH+7R76vHuhUWZPAcxk3pM1UipiVWKmnU9lT3yj/l3sXIIxZ60",
	"Y85LRRmnuM4rnkPqN3Lsv0ZDnHTNwLD3bZD4kR+9Ph8/xOrEYJhtR72HRL8EFGGSOXAL9mUVDgDCfz81",
	"uXn97rKuVBTn+u06VbRhSe7u/F5h4TevKNEb+TNx5CfgWFlgF2CvwbI3P15cspfnvxC+wLoQu2fHJ8ce",
	"mqYEzUuZTJOz45PjMwoGx6U3ccJLObl+NuG1kaVxkYPFVz6VjnGm4SYkoXJNPij7KYOCS+XpUHLnbowl",
	"YFDEPdR/Ea0WKrRJABE4/N6IVdhgaYTQuPCyVDLzYpOPLiy+YaGNHFvQrEN7G55y5tkWjOvXHHBIxv+9",
	"fnSchZ1wL9FpcntkeCmPqC7moI/gFi0/Qp77yWsmk0CYgLLVej9qVFM8/sbQsL+esmzJLa2Z1qU+fhQK",
	"LjXjTAEi2JSFjs2/5MyV4NvCVmzg16yxYfbs9OybL/CqVeQ9a3J9v2dn5NmLE8ZVueS6KsDKrGuxi6bi",
	"CwxtJkoLqb87Swt++92Lk8CebrFqYNB60knXsET1pakQ+AeuNNoF9J2enEZOlf5JlHt+crIXrLd1l2HF",
	"9Pb0p/qeC/Ym8Ihe36U9Ok/QXIEeJ/UbwMrqhtSv312ySxJgC2MZZ3VGYgx+/e7SjzwYi7uc2QLl2KJ/",
	"PyhHQZiG/qLgt7KoCsJr+441JymPhNIRfB4OlydRXKbJErgg/k0/JxeAR6+MuZLQT01fKkBiPZYFDcNU",
	"eLOeHvU059njz0mLFpOOCemoLxBhTFlFabWw4JbgfOcaunFc02vAqXp8j1RfP5edhiaZvu+3Mu8/3H3o",
	"FpuShKafkxwwth3IjL4GLf1hLGhRGqmRFohsCdmVrzaZ0Rqas8N+dM4DxWIheWCxGd24nBudf9PjfPNk",
	"ewvcKIwzdbg49Aq1hRJCA769SBOWHAGpni31gUO/Bc5ZWdnSUHSG4PLqD1WoR2N3QT1ps+GjjdoND0me",
	"12bPeXbVi+3PoJT50uDuVAYP7evlsu8q+Xd41+7BjScnhHXehgoya9d7AQowtpniV01ZUpKyEgbSE2mZ",
	"Q2OB2k9fG+Yr5gA9uuC2lJYEDePU3SPzC9om1n7wyl6/u6wr2kg5e/6rLGfpzk1S7d0ezdL2eHy1pfrr",
	"LJt7rCtdjP9asP2bAvUwlu1x56R/4Bhduhvst4ec3zrmqrI0FimWawWb0foHYCtz0Qi86o4/YJ1e2zHj",
	"Wsxyy8twpLLH0d/2s7uxGXYu3F+SJ9P5HGe3LDHT+U6HCNH/VqdUXOtIueomrf0GiDYilhfgN+1k+9gX",
	"FM23FwQR/8lNTSNJwz5VsP5sadp8dbBOaHteKTX+5XnkuPIu3Wlm0GLbvP4zh31m/fCFQN3pyqiN9WOg",
	"x98IdA5K70WRP9vrnqzSAtfiYitoNm5QDkryDT92Du6GTdELk47aXRlNy2ek5L/tB48tuWPaIJsDaFYf",
	"h7MVYPLwfiQ0Fe3N0pr0G4kb6Uba8T8EBb+jnD2AR+GiYX/+DC4oYrx5G7v/OHwCBj7cl4fovUw0CUPV",
	"h+DPIHhPQKPdyNPhzO81cbsEPHYo9tbf/d8b5zBsNMAPO8J4QMwe+WjhN5zfYZFs7qm3lkVqQ2kfBxop",
	"SCACFPzV5khtPDyldglwNKAHDJ8fYa/j7fRPxrLuVUKSJpVV9WWwm04mymRcLY3D6bOz07Pk7sPd/wIA",
	"AP//VwxXtzAyAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
