// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package queries

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateUser(ctx context.Context, name string) (sql.Result, error)
	CreateUserPassword(ctx context.Context, arg CreateUserPasswordParams) (sql.Result, error)
	DeleteUser(ctx context.Context, id uint32) error
	GetUser(ctx context.Context, id uint32) (*User, error)
	GetUserPasswordByUserID(ctx context.Context, userID uint32) (*UserPassword, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
