FROM golang:1.23.0-alpine3.20

WORKDIR /app

RUN go install github.com/air-verse/air@latest

# Copy go.mod first so we don't need to 
# download dependencies again for every source change
COPY go.mod .
RUN go mod download

EXPOSE 1323

CMD ["air", "-c", "config/.air.toml"]