openapi: "3.0.3"

info:
  title: Ping
  version: 1.0.0
servers:
- url: "http://{host}:{port}"
  description: Local development server
  variables:
    host:
      default: localhost
    port:
      default: '1323'
paths: {}
components:
  schemas:
    error:
      type: object
      description: Error code and underlying errors
      properties:
        code:
          type: string
          example: "validation_failed"
          description: "bad_request | unauthorized | forbidden | not_found | internal_server_error | validation_failed"
        message:
          type: string
          example: "there were some problems with the data you provided"
        validation_errors:
          type: object
          additionalProperties:
            type: string
          example: {"some_field": "the length must be between 1 and 20"}