openapi: "3.0.3"

info:
  title: Cashbunny
  version: 1.0.0
servers:
- url: "http://{host}:{port}"
  description: Local development server
  variables:
    host:
      default: localhost
    port:
      default: '1323'
components:
  securitySchemes:
    bearerAuth:
      $ref: './api.yaml#/components/securitySchemes/bearerAuth'
paths:
  /api/v1/secure/cashbunny/accounts:
    get:
      tags: 
        - v1
      operationId: cashbunny/listAccounts
      description: Retrieves all accounts
      summary: Retrieves all accounts
      security:
        - bearerAuth: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: './api.yaml#/components/schemas/error'
                  data:
                    example: ""
    post:
      tags: 
        - v1
      operationId: cashbunny/createAccount
      description: Creates an account
      summary: Creates an account
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                  example: savings
                name:
                  type: string
                  example: Test account
                description:
                  type: string
                  example: For savings
                balance:
                  type: number
                  example: 476000
                  description: unsigned floating number
                currency:
                  type: string
                  example: JPY
                type:
                  type: string
                  example: credit
                order_index:
                  type: number
                  example: 1
                  description: unsigned
              required:
                - name
                - balance
                - currency
                - type
                - order_index
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: './api.yaml#/components/schemas/error'