openapi: "3.0.3"

info:
  title: Ping
  version: 1.0.0
servers:
- url: "http://{host}:{port}"
  description: Local development server
  variables:
    host:
      default: localhost
    port:
      default: '1323'
paths:
  /api/v1/ping:
    get:
      tags: 
        - v1
      operationId: ping
      description: A convenience endpoint to check for connection
      summary: A convenience endpoint to check for connection
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  err:
                    $ref: './api.yaml#/components/schemas/error'
                  data:
                    type: string
                    description: Pong!
                    example: Pong!