openapi: "3.0.3"

info:
  title: Repeat
  version: 1.0.0
servers:
- url: "http://{host}:{port}"
  description: Local development server
  variables:
    host:
      default: localhost
    port:
      default: '1323'
paths:
  /api/v1/repeat:
    post:
      tags: 
        - v1
      operationId: repeat
      description: Returns the sent message, for testing purposes
      summary: Returns the sent message, for testing purposes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: Hey oh!
              required:
                - message
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    $ref: './api.yaml#/components/schemas/error'
                  data:
                    type: string
                    description: The message sent
                    example: Hey oh!