// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package user_password

import (
	"database/sql"
	"time"
)

type UserPassword struct {
	ID           uint32
	UserID       uint32
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}
