// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package user_password

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateUserPassword(ctx context.Context, db DBTX, arg CreateUserPasswordParams) (sql.Result, error)
	GetUserPasswordByUserID(ctx context.Context, db DBTX, userID uint32) (*UserPassword, error)
	UpdateUserPassword(ctx context.Context, db DBTX, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
