// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package cashbunny_account

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateAccount(ctx context.Context, db DBTX, arg CreateAccountParams) (sql.Result, error)
	CreateAccountCategory(ctx context.Context, db DBTX, arg CreateAccountCategoryParams) (sql.Result, error)
	DeleteAccount(ctx context.Context, db DBTX, arg DeleteAccountParams) error
	GetAccountCategoryByID(ctx context.Context, db DBTX, arg GetAccountCategoryByIDParams) (*CashbunnyAccountCategory, error)
	GetAccountCategoryByName(ctx context.Context, db DBTX, arg GetAccountCategoryByNameParams) (*CashbunnyAccountCategory, error)
	IncrementIndex(ctx context.Context, db DBTX, arg IncrementIndexParams) error
	ListAccountCategoriesByUserID(ctx context.Context, db DBTX, userID uint32) ([]*CashbunnyAccountCategory, error)
	ListAccounts(ctx context.Context, db DBTX, userID uint32) ([]*CashbunnyAccount, error)
	ListAccountsAndCategories(ctx context.Context, db DBTX, userID uint32) ([]*ListAccountsAndCategoriesRow, error)
}

var _ Querier = (*Queries)(nil)
