// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package cashbunny_account

import (
	"context"
	"database/sql"
)

const createAccount = `-- name: CreateAccount :execresult
INSERT INTO
  cashbunny_accounts (
    user_id,
    name,
    description,
    balance,
    currency,
    type,
    order_index
  )
VALUES
  (?, ?, ?, ?, ?, ?, ?)
`

type CreateAccountParams struct {
	UserID      uint32
	Name        string
	Description string
	Balance     float64
	Currency    string
	Type        string
	OrderIndex  uint32
}

func (q *Queries) CreateAccount(ctx context.Context, db DBTX, arg CreateAccountParams) (sql.Result, error) {
	return db.ExecContext(ctx, createAccount,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Balance,
		arg.Currency,
		arg.Type,
		arg.OrderIndex,
	)
}

const incrementIndex = `-- name: IncrementIndex :exec
UPDATE cashbunny_accounts
SET
  order_index = order_index + 1
WHERE
  user_id = ?
  AND order_index >= ?
`

type IncrementIndexParams struct {
	UserID     uint32
	OrderIndex uint32
}

func (q *Queries) IncrementIndex(ctx context.Context, db DBTX, arg IncrementIndexParams) error {
	_, err := db.ExecContext(ctx, incrementIndex, arg.UserID, arg.OrderIndex)
	return err
}

const listAccounts = `-- name: ListAccounts :many
SELECT
  id, user_id, name, description, balance, currency, type, order_index, created_at, updated_at, deleted_at
FROM
  cashbunny_accounts
WHERE
  user_id = ?
ORDER BY
  order_index
`

func (q *Queries) ListAccounts(ctx context.Context, db DBTX, userID uint32) ([]*CashbunnyAccount, error) {
	rows, err := db.QueryContext(ctx, listAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*CashbunnyAccount{}
	for rows.Next() {
		var i CashbunnyAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Balance,
			&i.Currency,
			&i.Type,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
