version: "2"
overrides:
  go:
    overrides:
      - db_type: "decimal"
        go_type:
          type: "float64"
sql:
  - engine: "mysql"
    queries: "../db/service/user/query.sql"
    schema: "../db/migration"
    gen:
      go:
        sql_package: "database/sql"
        out: "../db/service/user"
        emit_methods_with_db_argument: true
        emit_interface: true
        emit_result_struct_pointers: true
        omit_unused_structs: true
        emit_empty_slices: true
  - engine: "mysql"
    queries: "../db/service/user_password/query.sql"
    schema: "../db/migration"
    gen:
      go:
        sql_package: "database/sql"
        out: "../db/service/user_password"
        emit_methods_with_db_argument: true
        emit_interface: true
        emit_result_struct_pointers: true
        omit_unused_structs: true
        emit_empty_slices: true
  - engine: "mysql"
    queries: "../db/service/cashbunny_account/query.sql"
    schema: "../db/migration"
    gen:
      go:
        sql_package: "database/sql"
        out: "../db/service/cashbunny_account"
        emit_methods_with_db_argument: true
        emit_interface: true
        emit_result_struct_pointers: true
        omit_unused_structs: true
        emit_empty_slices: true
  - engine: "mysql"
    queries: "../db/service/cashbunny_category/query.sql"
    schema: "../db/migration"
    gen:
      go:
        sql_package: "database/sql"
        out: "../db/service/cashbunny_category"
        emit_methods_with_db_argument: true
        emit_interface: true
        emit_result_struct_pointers: true
        omit_unused_structs: true
        emit_empty_slices: true