version: "2"
sql:
  - engine: "mysql"
    queries: "../db/query"
    schema: "../db/migration"
    gen:
      go:
        sql_package: "database/sql"
        emit_db_tags: true
        package: "db"
        out: "../db/sqlc"
        emit_interface: true
        emit_result_struct_pointers: true
        emit_empty_slices: true
        overrides:
          - db_type: "decimal"
            go_type:
              type: "float64"