// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package cashbunny_transaction

import (
	"database/sql"
	"time"
)

type CashbunnyTransaction struct {
	ID           uint32
	UserID       uint32
	Description  string
	TransactedAt time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}
