// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package cashbunny_transaction

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateTransaction(ctx context.Context, db DBTX, arg CreateTransactionParams) (sql.Result, error)
	ListTransactionsByUserID(ctx context.Context, db DBTX, userID uint32) ([]*CashbunnyTransaction, error)
}

var _ Querier = (*Queries)(nil)
