// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package queries

import (
	"database/sql"
	"time"
)

type CashbunnyAccount struct {
	ID          uint32
	UserID      uint32
	Category    string
	Name        string
	Description string
	Currency    string
	OrderIndex  uint32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type CashbunnyRecurrenceRule struct {
	ID        uint32
	Freq      string
	Dtstart   time.Time
	Count     int32
	Interval  int32
	Until     time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CashbunnyScheduledTransaction struct {
	ID            uint32
	UserID        uint32
	CategoryID    sql.NullInt32
	SrcAccountID  uint32
	DestAccountID uint32
	Description   string
	Amount        float64
	Currency      string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     sql.NullTime
}

type CashbunnyTransaction struct {
	ID                     uint32
	UserID                 uint32
	ScheduledTransactionID sql.NullInt32
	CategoryID             sql.NullInt32
	SrcAccountID           uint32
	DestAccountID          uint32
	Description            string
	Amount                 float64
	Currency               string
	TransactedAt           time.Time
	CreatedAt              time.Time
	UpdatedAt              time.Time
	DeletedAt              sql.NullTime
}

type CashbunnyTransactionCategory struct {
	ID        uint32
	UserID    uint32
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type CashbunnyTransactionCategoryAllocation struct {
	ID         uint32
	UserID     uint32
	CategoryID uint32
	Amount     float64
	Currency   string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DeletedAt  sql.NullTime
}

type CashbunnyUserCurrency struct {
	ID           uint32
	UserID       uint32
	CurrencyCode string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type CashbunnyUserPreference struct {
	ID        uint32
	UserID    uint32
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type User struct {
	ID         uint32
	Name       string
	Email      string
	DisabledAt sql.NullTime
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DeletedAt  sql.NullTime
}

type UserPassword struct {
	ID           uint32
	UserID       uint32
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}

type UserSystemPreference struct {
	ID        uint32
	UserID    uint32
	Language  sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}
