// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package cashbunny_category

import (
	"database/sql"
	"time"
)

type CashbunnyCategory struct {
	ID          uint32
	UserID      uint32
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}
