// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package cashbunny_category

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateCategory(ctx context.Context, db DBTX, arg CreateCategoryParams) (sql.Result, error)
	GetCategoryByID(ctx context.Context, db DBTX, arg GetCategoryByIDParams) (*CashbunnyCategory, error)
	ListCategoriesByUserID(ctx context.Context, db DBTX, userID uint32) ([]*CashbunnyCategory, error)
}

var _ Querier = (*Queries)(nil)
